DATA CLASS;
	SET SASHELP.CLASS;
	
PROC SORT DATA=CLASS OUT=SORTED;
	BY DESCENDING AGE;
	
PROC PLOT DATA=SORTED;
	PLOT HEIGHT * AGE="*" / VAXIS=50 TO 75 BY 0.2
							HAXIS=11 TO 16 BY 1;

PROC MEANS DATA = CLASS;
	VAR HEIGHT;
	CLASS AGE;
RUN;