DATA FISH;
	SET SASHELP.FISH;

PROC SORT DATA=FISH OUT = SORTED;
	BY DESCENDING WEIGHT;
	
PROC PLOT DATA=FISH;
	PLOT WEIGHT * SPECIES ="*" / VAXIS = 0 TO 1650 BY 50;
							
PROC MEANS DATA = FISH STDDEV;
	VAR WEIGHT;
	CLASS SPECIES;
	
DATA CLASS;
	SET SASHELP.CLASS;

PROC SORT DATA=CLASS OUT=SORTED;
	BY DESCENDING AGE;	
	
PROC PLOT DATA=SORTED;
	PLOT WEIGHT * AGE="*" / VAXIS=50 TO 160 BY 10
							HAXIS=10 TO 20 BY 1;


RUN;