	
DATA WSC;
	SET SASHELP.HEART;
	KEEP WEIGHT_STATUS CHOLESTEROL;
	
DATA WS;
	SET WSC (OBS=1000);
	IF WEIGHT_STATUS = "Overweight" THEN WS = 1;
	ELSE IF WEIGHT_STATUS = "Normal" THEN WS = 0;
	ELSE WS = -1;

PROC CORR DATA=WS PLOTS=MATRIX;
	VAR WS CHOLESTEROL;
	
RUN;