DATA CARS;
	SET SASHELP.CARS;
	KEEP MAKE TYPE;

PROC TEMPLATE;
	DEFINE STATGRAPH pie;
		BEGINGRAPH; 
			LAYOUT REGION;
				PIECHART CATEGORY = TYPE /
					DATALABELLOCATION = OUTSIDE 
					CATEGORYDIRECTION = CLOCKWISE 
					START = 0 NAME = 'pie';
				DISCRETELEGEND 'pie' /
					TITLE = 'Rate of car types';
			ENDLAYOUT; 
		ENDGRAPH;
	END;
	
PROC SGRENDER DATA=CARS TEMPLATE = pie; 

RUN;