DATA FISH;
	SET SASHELP.FISH;
	
PROC UNIVARIATE DATA=FISH NOPRINT;
	HISTOGRAM HEIGHT / MIDPOINTS = 1 TO 19 BY 1;
	
PROC SGPLOT DATA=FISH;
	VBAR SPECIES;
	TITLE "Frequency of fish specises";

PROC TEMPLATE;
	DEFINE STATGRAPH pie;
		BEGINGRAPH; 
			LAYOUT REGION;
				PIECHART CATEGORY = SPECISES /
					DATALABELLOCATION = OUTSIDE 
					CATEGORYDIRECTION = CLOCKWISE 
					START = 0 NAME = 'pie';
				DISCRETELEGEND 'pie' /
					TITLE = 'Rate of car specises';
			ENDLAYOUT; 
		ENDGRAPH;
	END;
	
PROC SGRENDER DATA=FISH TEMPLATE = pie; 
	
RUN;

	