DATA SCORE1;
	INFILE "/folders/myshortcuts/R_practice/Week_2/score1.txt";
	INPUT GENDER$ KOR MAT ENG SCI;
	
DATA SCORE2;
	INFILE "/folders/myshortcuts/R_practice/Week_2/score2.txt";
	INPUT GENDER$ KOR MAT ENG SCI;
	
DATA SCORES;
	SET SCORE1 SCORE2;
	
DATA PASS;
	INFILE "/folders/myshortcuts/R_practice/Week_2/pass.txt";
	LENGTH PASS$ 9;
	INPUT GENDER$ PASS$;
	
DATA SCORES_PASS;
	MERGE SCORES PASS;
	
DATA TF;
	SET SCORES_PASS;
	IF PASS="불합격" THEN PASS="F";
	ELSE IF PASS="합격" THEN PASS="T";

DATA MERGE_12;
	MERGE SCORES TF;
	TOTAL=KOR+MAT+ENG+SCI;
	AVERAGE=TOTAL/4;
	IF AVERAGE >= 80 THEN PRIZE="YES";
	ELSE PRIZE="NO";


RUN;