DATA SCORE1;
	INFILE "/folders/myshortcuts/R_practice/Week_2/score1.txt";
	INPUT GEN$ KOR MAT ENG SCI;
	
DATA SCORE2;
	INFILE "/folders/myshortcuts/R_practice/Week_2/score2.txt";
	INPUT GEN$ KOR MAT ENG SCI;
	
DATA SCORES;
	SET SCORE1 SCORE2;
	TOTAL=KOR*2+MAT*4+SCI*2+ENG*2;
	IF TOTAL>=800 THEN NOTE="GREAT";
	ELSE IF TOTAL>=600 THEN NOTE="GOOD";
	ELSE IF TOTAL>=400 THEN NOTE="OK";
	ELSE NOTE="F";

DATA ONLY_M_T_N;
	SET SCORES;
	KEEP MAT TOTAL NOTE;
	PROC PRINT DATA=ONLY_M_T_N;