DATA HOLIDAY;
	SET SASHELP.HOLIDAY;
	
PROC TEMPLATE;
	DEFINE STATGRAPH pie;
		BEGINGRAPH; 
			LAYOUT REGION;
				PIECHART CATEGORY = MONTH /
					DATALABELLOCATION = OUTSIDE 
					CATEGORYDIRECTION = CLOCKWISE 
					START = 0 NAME = 'pie';
				DISCRETELEGEND 'pie' /
					TITLE = 'Rate of holiday';
			ENDLAYOUT; 
		ENDGRAPH;
	END;
	
PROC SGRENDER DATA=HOLIDAY TEMPLATE = pie; 
	
DATA SHOES;
	SET SASHELP.SHOES;	

PROC SGPLOT DATA=SHOES;
	VBAR PRODUCT / GROUP=REGION;
	TITLE "Frequency of product";

RUN;